### ISSUE TITLE
Create Forms

### ISSUE THREAD

**Issue by SharifaTaimur** [lalidiaz/WWC-Social-Good-2022#1]
- [ ] Creation of registration form
- [ ] Creation of sign in form
- [ ] Creation of submit trip details form

**Comment by lalidiaz** [comment]
@SharifaTaimur from what I understood this should be a pull request 🙂 let me know if you need some help!

**Comment by SharifaTaimur** [comment]
> @SharifaTaimur from what I understood this should be a pull request 🙂 let me know if you need some help!

@lalidiaz No this was supposed to be an open issue and should only be closed once the changes have been merged to the main branch. ( So this practice is usually used to keep track of the features to be implemented into the project , although here our project is small and might not seem necessary , but its just a default habit I do at work and did it here too 👯 )

**Comment by lalidiaz** [comment]
@SharifaTaimur sorry! I got confused about this and close it 😬 😂

**Comment by lalidiaz** [comment]
I learned something new with this 🥰 https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues wohooooooo 🎉 thanks @SharifaTaimur
